<a href="https://colab.research.google.com/github/juno2856/deeplearning/blob/master/NLP/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_20220531.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.2 MB 5.2 MB/s 
     |████████████████████████████████| 596 kB 47.2 MB/s 
     |████████████████████████████████| 6.6 MB 32.2 MB/s 
     |████████████████████████████████| 86 kB 5.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from transformers import pipeline

classifier =  pipeline('sentiment-analysis', framework = 'tf')
classifier('We are very happy to include pipeline into the transformers repository')

# 모델설정을 안해서 distilbert-base-uncased-finetuned-sst-2-english 자동설정

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9968750476837158}]

In [ ]:
classifier('I hate nlp')

[{'label': 'NEGATIVE', 'score': 0.9990854263305664}]

- Processors
- Tokenizer
- Model
- Optimization
- Trainer
- Config

# 1. Model

- from_pretrained : 모델을 로드
- 

In [ ]:
from transformers import TFBertForPreTraining
model = TFBertForPreTraining.from_pretrained('bert-base-cased')

print(model.__class__)

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/502M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForPreTraining.

All the layers of TFBertForPreTraining were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForPreTraining for predictions without further training.


<class 'transformers.models.bert.modeling_tf_bert.TFBertForPreTraining'>


- 2. 모델의 정보를 주지 않아도, model id를 입력하면 불러오기 가능

In [ ]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained('bert-base-cased')

print(model.__class__)

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


<class 'transformers.models.bert.modeling_tf_bert.TFBertModel'>


## 2. Tokenizer

- bert-base-uncased : 108MB 파라미터의 기본 모델 코퍼스는 영문 대소문자 구분을 없앤다.(소문자화)
- bert-large-cased : 340MB 파라미터의 대형 모델이면서, 코퍼스는 영문 대소문자 구분을 유지
- bert-base-multilingual-cased: 108MB 파라미터의 기본 모델 코퍼스는 다국어 대소문자 구분 유지

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

In [ ]:
input = ["Hello I'm a student",
         "And another student",
         "And the very very sleep"]

encoded = tokenizer(input)
print(encoded)

{'input_ids': [[101, 8667, 146, 112, 182, 170, 2377, 102], [101, 1262, 1330, 2377, 102], [101, 1262, 1103, 1304, 1304, 2946, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}


In [ ]:
batch = tokenizer(input, padding = True, truncation = True, return_tensors = 'tf')
print(batch)

{'input_ids': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 101, 8667,  146,  112,  182,  170, 2377,  102],
       [ 101, 1262, 1330, 2377,  102,    0,    0,    0],
       [ 101, 1262, 1103, 1304, 1304, 2946,  102,    0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}


## 3. Processor
raw data를 가공하여 model에 태울 수 있는 형태를 만들어주는 작업을 해주는 클래스

In [ ]:
class DataProcessor:
    """sequence classification을 위해 data를 처리하는 기본 processor"""

    def get_example_from_tensor_dict(self, tensor_dict):
        """
        tensor dict에서 example을 가져오는 메소드
        """
        raise NotImplementedError()

    def get_train_examples(self, data_dir):
        """train data에서 InputExample 클래스를 가지고 있는 것들을 모으는 메소드"""
        raise NotImplementedError()

    def get_dev_examples(self, data_dir):
        """dev data(validation data)에서 InputExample 클래스를 가지고 있는 것들을 모으는 메소드"""
        raise NotImplementedError()

    def get_test_examples(self, data_dir):
        """test data에서 InputExample 클래스를 가지고 있는 것들을 모으는 메소드"""
        raise NotImplementedError()

    def get_labels(self):
        """data set에 사용되는 라벨들을 리턴하는 메소드"""
        raise NotImplementedError()

    def tfds_map(self, example):
        """
        tfds(tensorflow-datasets)에서 불러온 데이터를 DataProcessor에 알맞게 가공해주는 메소드
        """
        if len(self.get_labels()) > 1:
            example.label = self.get_labels()[int(example.label)]
        return example

    @classmethod
    def _read_tsv(cls, input_file, quotechar=None):
        """tab으로 구분된 .tsv파일을 읽어들이는 클래스 메소드"""
        with open(input_file, "r", encoding="utf-8-sig") as f:
            return list(csv.reader(f, delimiter="\t", quotechar=quotechar))

## 4. config
fairseq https://fairseq.readthedocs.io/en/latest/
fast.aihttps://docs.fast.ai/

In [ ]:
from transformers import BertConfig

config = BertConfig.from_pretrained("bert-base-cased")

print(config.__class__)
print(config)

<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.19.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}



In [ ]:
from transformers import AutoConfig

config = AutoConfig.from_pretrained("bert-base-cased")

print(config.__class__)
print(config)

<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertConfig {
  "_name_or_path": "bert-base-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.19.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}



In [ ]:
model= TFBertForPreTraining.from_pretrained("bert-base-cased")

config = model.config
print(config.__class__)
print(config)

All model checkpoint layers were used when initializing TFBertForPreTraining.

All the layers of TFBertForPreTraining were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForPreTraining for predictions without further training.


<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertConfig {
  "_name_or_path": "bert-base-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.19.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}



## 5. Trainer

In [ ]:
# tf.keras.model API를 이용해 활용하는 경우의 예시

import tensorflow as tf
from transformers import TFAutoModelForPreTraining, AutoTokenizer

model = TFAutoModelForPreTraining.from_pretrained('bert-base-cased')
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

All model checkpoint layers were used when initializing TFBertForPreTraining.

All the layers of TFBertForPreTraining were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForPreTraining for predictions without further training.


In [ ]:
sentence = "Hello, This is test for ert TFmodel."

input_ids = tf.constant(tokenizer.encode(sentence, add_special_tokens = True))[None, :]

In [ ]:
input_ids

<tf.Tensor: shape=(1, 15), dtype=int32, numpy=
array([[  101,  8667,   117,  1188,  1110,  2774,  1111, 14044,  1204,
          157,  2271,  3702,  6738,   119,   102]], dtype=int32)>

In [ ]:
optimizer = tf.keras.optimizers.Adam(learning_rate = 3e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

model.compile(optimizer = optimizer, loss = loss)
pred = model.predict(input_ids)

In [ ]:
print("----Results-----")
print(pred)

----Results-----
TFBertForPreTrainingOutput(loss=None, prediction_logits=array([[[ -7.3711185,  -7.3328176,  -7.4321623, ...,  -6.180566 ,
          -5.850667 ,  -6.3305726],
        [ -7.8735094,  -8.083443 ,  -7.9078264, ...,  -6.4807653,
          -6.348704 ,  -6.8071527],
        [-11.615899 , -11.629044 , -11.534765 , ...,  -8.287493 ,
          -8.601618 ,  -9.565309 ],
        ...,
        [ -3.4737644,  -4.0366864,  -2.749408 , ...,  -4.283107 ,
          -2.4199238,  -3.0901816],
        [-12.112164 , -11.97305  , -11.763897 , ...,  -8.980633 ,
          -9.083221 , -10.397418 ],
        [-10.254294 , -10.679947 , -10.665481 , ...,  -8.322065 ,
          -9.148861 , -10.193973 ]]], dtype=float32), seq_relationship_logits=array([[ 1.625331 , -0.7076506]], dtype=float32), hidden_states=None, attentions=None)


In [ ]:
# TFTrainer 사용 예시
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Optional

import tensorflow as tf
import tensorflow_datasets as tfds
from transformers import(
    TFAutoModelForSequenceClassification,
    TFTrainer,
    TFTrainingArguments,
    AutoConfig,
    AutoTokenizer,
    glue_convert_examples_to_features,
)

In [ ]:
# TFTrainingArguments 정의
training_args = TFTrainingArguments(
    output_dir = './' ,# output이 저장될 경로
    num_train_epochs = 1, # train 시킬 총 epochs
    per_device_train_batch_size = 16, # 각 device 당 batch_size
    per_device_eval_batch_size = 64,  # evaluation 시에 batch_size
    warmup_steps = 500,  # learning rate scheduler에 따른 warmup_step 설정
    weight_decay = 0.01,
    logging_dir = './', # log들이 저장될 경로
    do_train = True, # train 수행 여부
    do_eval = True, # eval 수행여부
    eval_steps = 1000

)

In [ ]:
# model, tokenizer 생성
model_name_or_path = 'bert-base-uncased'
with training_args.strategy.scope(): # training_args가 영향을 미치는 model 범위를 지정
    model = TFAutoModelForSequenceClassification.from_pretrained(
        model_name_or_path,
        from_pt = bool(".bin" in model_name_or_path),
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_name_or_path
    )

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/511M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

In [ ]:
# 데이터 생성
ds, info = tfds.load('glue/mrpc', with_info = True)
train_dataset = glue_convert_examples_to_features(ds['train'],tokenizer, 128,'mrpc')
train_dataset = train_dataset.apply(tf.data.experimental.assert_cardinality(info.splits['train'].num_examples))

# TFTrainer 생성
trainer = TFTrainer(
    model = model,  # 학습시킬 model
    args = training_args, # TFTrainingArguments를 통해 설정한 arguments
    train_dataset = train_dataset, # training dataset

)

# 학습을 진행
trainer.train()

# 테스트
test_dataset = glue_convert_examples_to_features(ds['test'], tokenizer, 128, 'mrpc')
test_dataset = test_dataset.apply(tf.data.experimental.assert_cardinality(info.splits['test'].num_examples))
trainer.evaluate(test_dataset)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/glue/mrpc/1.0.0.incompleteDPNRPL/glue-train.tfrecord


  0%|          | 0/3668 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/glue/mrpc/1.0.0.incompleteDPNRPL/glue-validation.tfrecord


  0%|          | 0/408 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/glue/mrpc/1.0.0.incompleteDPNRPL/glue-test.tfrecord


  0%|          | 0/1725 [00:00<?, ? examples/s]

Dataset glue downloaded and prepared to /root/tensorflow_datasets/glue/mrpc/1.0.0. Subsequent calls will reuse this data.


/usr/local/lib/python3.7/dist-packages/transformers/data/processors/glue.py:66: FutureWarning: This function will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py
  warnings.warn(DEPRECATION_WARNING.format("function"), FutureWarning)
/usr/local/lib/python3.7/dist-packages/transformers/data/processors/glue.py:174: FutureWarning: This processor will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py
  warnings.warn(DEPRECATION_WARNING.format("processor"), FutureWarning)
/usr/local/lib/python3.7/dist-packages/transformers/trainer_tf.py:120: FutureWarning: The class `TFTrainer` is deprec

{'eval_loss': 0.4594985467416269}

## huggingface로 imdb 긍부정 분류하기

In [ ]:
!pip install transformers
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 346 kB 5.2 MB/s 
     |████████████████████████████████| 86 kB 5.9 MB/s 
     |████████████████████████████████| 1.1 MB 45.0 MB/s 
     |████████████████████████████████| 140 kB 51.8 MB/s 
     |████████████████████████████████| 212 kB 54.7 MB/s 
     |████████████████████████████████| 127 kB 26.0 MB/s 
     |████████████████████████████████| 94 kB 3.2 MB/s 
     |████████████████████████████████| 144 kB 57.9 MB/s 
     |████████████████████████████████| 271 kB 52.4 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: dill
    Found existing installation: dill 0.3.5.1
    Uninstalling dill-0.3.5.1:
      Successfully u

In [ ]:
!wget http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -xf aclImdb_v1.tar.gz

--2022-05-31 07:58:36--  http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
Resolving ai.stanford.edu (ai.stanford.edu)... 171.64.68.10
Connecting to ai.stanford.edu (ai.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84125825 (80M) [application/x-gzip]
Saving to: ‘aclImdb_v1.tar.gz’

aclImdb_v1.tar.gz   100%[===================>]  80.23M  25.0MB/s    in 3.2s    

2022-05-31 07:58:39 (25.0 MB/s) - ‘aclImdb_v1.tar.gz’ saved [84125825/84125825]



In [ ]:
import torch
from transformers import DistilBertTokenizerFast
from transformers import DistilBertConfig
from transformers import DistilBertForSequenceClassification, Trainer, TrainingArguments
from pathlib import Path
from sklearn.model_selection import train_test_split

In [ ]:
def read_imdb_split(split_dir):
    split_dir = Path(split_dir) # 경로설정 aclImdb/train
    texts = []
    labels = []
    for label_dir in ["pos", "neg"]: # label_dir = pos
        for text_file in (split_dir/label_dir).iterdir(): # aclImdb/train/pos
            texts.append(text_file.read_text())
            labels.append(0 if label_dir is "neg" else 1)
    return texts, labels

# 1. 데이터 불러오기

In [ ]:
train_texts, train_labels = read_imdb_split('aclImdb/train')
test_texts, test_labels = read_imdb_split('aclImdb/test')

In [ ]:
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [ ]:
train_texts, val_texts, train_labels, val_labels = train_test_split(train_texts, train_labels, test_size=0.2)

In [ ]:
train_encodings = tokenizer(train_texts, truncation=True, padding=True)
val_encodings = tokenizer(val_texts, truncation=True, padding=True)
test_encodings = tokenizer(test_texts, truncation=True, padding=True)

In [ ]:
print(train_encodings[0])

Encoding(num_tokens=512, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])


In [ ]:
class IMDbDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    
    def __getitem__(self, idx):
        item = {key : torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
            
    def __len__(self):
        return len(self.labels)

In [ ]:
train_dataset = IMDbDataset(train_encodings, train_labels)
val_dataset = IMDbDataset(val_encodings, val_labels)
test_dataset = IMDbDataset(test_encodings, test_labels)

In [ ]:
config = DistilBertConfig.from_pretrained('distilbert-base-uncased',\
                                 vocab_size = 30522, \
                                 max_position_embedding = 512, \
                                 sinusoidal_pos_embds = False, \
                                 n_layer = 4, \
                                 n_heads= 8, \
                                 dim = 768, \
                                 hidden_dim = 3072, \
                                 dropout=0.1, \
                                 attention_dropout= 0.1, \
                                 activation='gelu')

In [ ]:
training_args = TrainingArguments(
    output_dir = './results',
    num_train_epochs = 1,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 64,
    warmup_steps = 500,
    weight_decay=0.01,
    logging_dir = './logs',
    logging_steps = 100,
)

In [ ]:
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', config=config)

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.bias', 'vocab_projector.weight', 'vocab_layer_norm.weight', 'vocab_projector.bias', 'vocab_layer_norm.bias', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.bias', 'pre_classifier.weight', 'classi

In [ ]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = val_dataset
)

trainer.train()

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 20000
  Num Epochs = 1
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 1250


Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin


Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=1250, training_loss=0.3434802749633789, metrics={'train_runtime': 2139.8133, 'train_samples_per_second': 9.347, 'train_steps_per_second': 0.584, 'total_flos': 2649347973120000.0, 'train_loss': 0.3434802749633789, 'epoch': 1.0})

In [ ]:
from datasets import load_metric
from torch.utils.data import DataLoader
from tqdm import tqdm

In [ ]:
metric = load_metric("accuracy")
test_dataloader = DataLoader(test_dataset, batch_size = 128)
model.eval()

for batch in tqdm(test_dataloader):
    batch = {k : v.to("cuda") for k,v in batch.items()}
    with torch.no_grad():
        outputs = model(**batch)
    logits = outputs.logits
    predictions = torch.argmax(logits, dim = -1)
    metrics.add_batch(predictions = predictions, references = batch["labels"])

metric.compute()    

100%|██████████| 196/196 [15:22<00:00,  4.71s/it]


NameError: ignored