<a href="https://colab.research.google.com/github/juno2856/deeplearning/blob/master/NLP/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_20220530.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


```
from transformers import TFAutoModel, AutoTokenizer
model = TFAutoModel.from_pretrained("<model_name>")
tokenizer = AutoTokenizer.from_pretrained("<model_name>")
```

## Tokenizer 실습

In [ ]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer

In [ ]:
model_name = "bert-base-multilingual-cased"

model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name) # 모델에 해당하는 tokenizer가 자동적으로 불러와짐

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
print(tokenizer.vocab_size)

119547


In [ ]:
for i,key in enumerate(tokenizer.get_vocab()):
  print(key)
  if i>20:
    break

দেয়
останній
鋤
咕
գրող
minut
##wiony
##стей
##誕
pagastā
##erit
##ˈ
##昨
##nskog
talents
Bd
talk
##bauen
##缩
##ที่
##踩
압


In [ ]:
text = '이순신은 조선 중기의 무신이다.'

In [ ]:
print(type(tokenizer))

<class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>


In [ ]:
tokenized_input_text = tokenizer(text, return_tensors='pt') # tensor = pytorch기반

In [ ]:
for key,value in tokenized_input_text.items():
  print("{} : \n\t {}".format(key, value))
  # input_ids : 단어장의 인덱스
  # token_type_ids : 2개의 문장을 넣을 때 <SEP>을 기준으로 0과 1을 나타내준다.
  # attention_mask : 패딩 아닌 =  1, 패딩인 = 0

input_ids : 
	 tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids : 
	 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask : 
	 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [ ]:
print(tokenized_input_text['input_ids']) # input text를 tokenizeing 한 후 vocab id
print(tokenized_input_text.input_ids)

tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])


In [ ]:
print(tokenized_input_text['token_type_ids']) #segment id(sent A or sentB)
print(tokenized_input_text.token_type_ids)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [ ]:
print(tokenized_input_text['attention_mask']) # special token (pad, cis, sep) or not
print(tokenized_input_text.attention_mask)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [ ]:
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)  # ## 앞의 단어와 이어짐

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.']


In [ ]:
input_ids = tokenizer.encode(text, add_special_tokens = True)
print(input_ids)

[101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102]


In [ ]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

[CLS] 이순신은 조선 중기의 무신이다. [SEP]


# option

In [ ]:
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선']


In [ ]:
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906]


In [ ]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선


In [ ]:
print(tokenizer.pad_token)

[PAD]


In [ ]:
tokenizer.pad_token_id

0

In [ ]:
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = 'max_length'
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [ ]:
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = 'max_length'
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선 중기의 무신이다. [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


# 새로운 토큰을 추가해보자!

In [ ]:
text = '깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요'

# tokenized_text
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('tokenized_text\n', tokenized_text)

# input_ids
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('input_ids\n', input_ids)

# decoded_ids

decoded_ids = tokenizer.decode(input_ids)
print('decoded_ids\n',decoded_ids)

tokenized_text
 ['[UNK]', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '[UNK]', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '[UNK]', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요', '[PAD]', '[PAD]']
input_ids
 [100, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 100, 8982, 28188, 119121, 119060, 119060, 119060, 100, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549, 0, 0]
decoded_ids
 [UNK] 리뿔이 뜨럽거 므리커럭이 [UNK] 나오애쇼쇼쇼 [UNK] 청쇼랴료다혀뚜요 [PAD] [PAD]


In [ ]:
added_token_num = tokenizer.add_tokens(['깟빼뜨랑', '케쇼쇼쇽', '우뤼갸갸갸'])
print(add_token_num)

3


In [ ]:
# tokenized_text
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('tokenized_text\n', tokenized_text)

# input_ids
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('input_ids\n', input_ids)

# decoded_ids

decoded_ids = tokenizer.decode(input_ids)
print('decoded_ids\n',decoded_ids)

tokenized_text
 ['깟빼뜨랑', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '케쇼쇼쇽', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '우뤼갸갸갸', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요', '[PAD]', '[PAD]']
input_ids
 [119547, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 119548, 8982, 28188, 119121, 119060, 119060, 119060, 119549, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549, 0, 0]
decoded_ids
 깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요 [PAD] [PAD]


In [ ]:
text = "[juno]이순신은 조선 중기의 무신이다.[/juno]"

# tokenized_text
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('tokenized_text\n', tokenized_text)

# input_ids
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 30,
    padding = 'max_length'
)
print('input_ids\n', input_ids)

# decoded_ids

decoded_ids = tokenizer.decode(input_ids)
print('decoded_ids\n',decoded_ids)

tokenized_text
 ['[', 'ju', '##no', ']', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[', '/', 'ju', '##no', ']', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
input_ids
 [164, 23005, 10343, 166, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 164, 120, 23005, 10343, 166, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
decoded_ids
 [ juno ] 이순신은 조선 중기의 무신이다. [ / juno ] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


In [ ]:
text = "[juno]이순신은 조선 중기의 무신이다.[/juno]"

added_token_num += tokenizer.add_special_tokens({"additional_special_tokens" : ["[juno]", "[/juno]"]})

# tokenized_text
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
)
print('tokenized_text\n', tokenized_text)

# input_ids
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
)

print('input_ids\n', input_ids)

# decoded_ids

decoded_ids = tokenizer.decode(input_ids)
print('decoded_ids\n',decoded_ids)

tokenized_text
 ['[juno]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[/juno]']
input_ids
 [119550, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 119551]
decoded_ids
 [juno] 이순신은 조선 중기의 무신이다. [/juno]


In [ ]:
# single input
single_seg_input = tokenizer("이순신은 조선 중기의 무신이다.")

# Multiple input
multi_seg_input = tokenizer('이순신은 조선 중기의 무신이다.', "그는 임진왜란을 승리로 이끌었다.")

In [ ]:
print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(single_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(single_seg_input['input_ids']))
print("Single segment type : {}".format(single_seg_input['token_type_ids']))

# Segments
print()
print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(multi_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(multi_seg_input['input_ids']))
print("Single segment type : {}".format(multi_seg_input['token_type_ids']))

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]', '그는', '임', '##진', '##왜', '##란', '##을', '승', '##리로', '이', '##끌', '##었다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102, 17889, 9644, 18623, 119164, 49919, 10622, 9484, 100434, 9638, 118705, 17706, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


# Bert 모델 테스트

In [ ]:
text = "이순신은 [MASK] 중기의 무신이다."
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

['이', '##순', '##신', '##은', '[MASK]', '중', '##기의', '무', '##신', '##이다', '.']


In [ ]:
from transformers import pipeline

nlp_fill = pipeline('fill-mask', model = model_name)
nlp_fill("지금 목이[MASK] ")

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.035984668880701065,
  'sequence': '지금 목이.',
  'token': 119,
  'token_str': '.'},
 {'score': 0.03488186001777649,
  'sequence': '지금 목이도',
  'token': 12092,
  'token_str': '##도'},
 {'score': 0.031330253928899765,
  'sequence': '지금 목이 목',
  'token': 9284,
  'token_str': '목'},
 {'score': 0.02610834315419197,
  'sequence': '지금 목이기',
  'token': 12310,
  'token_str': '##기'},
 {'score': 0.025743363425135612,
  'sequence': '지금 목이강',
  'token': 47181,
  'token_str': '##강'}]

In [ ]:
tokens_pt = tokenizer("이순신은 조선 중기의 무신이다.", return_tensors = 'pt')

for key, value in tokens_pt.items():
  print("{} : \n\t{}".format(key, value))

outputs = model(**tokens_pt)
last_hidden_state =  outputs.last_hidden_state
pooler_output = outputs.pooler_output

print("\nToken wise output : {}. Pooled output : {}".format(last_hidden_state.shape, pooler_output.shape))

input_ids : 
	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids : 
	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask : 
	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Token wise output : torch.Size([1, 13, 768]). Pooled output : torch.Size([1, 768])


In [ ]:
print(pooler_output) # 모델의 출력결과도 획득가능!

tensor([[ 2.3151e-01, -8.0099e-02, -1.4249e-01, -1.6500e-01,  4.0655e-02,
         -1.0855e-01, -8.1335e-02,  1.8238e-01, -2.5709e-01,  1.7708e-01,
          5.5793e-02,  2.1646e-01, -2.6028e-01, -1.1805e-01,  1.6879e-01,
          2.2665e-01,  1.6693e-01, -1.4605e-01, -3.3806e-01, -2.5438e-04,
         -9.9437e-01, -3.0201e-01,  7.8168e-02, -2.0071e-01, -2.2053e-02,
          1.8374e-01,  7.8908e-02,  2.7492e-01,  1.5742e-01, -1.8704e-03,
         -1.9677e-01, -9.9644e-01,  5.8323e-01,  2.5800e-01,  1.8723e-01,
         -2.3858e-01,  5.7414e-02,  2.9294e-01,  2.0999e-01, -3.3407e-01,
          9.6668e-02, -1.3142e-01,  1.4946e-01, -2.3270e-01, -1.2149e-01,
         -2.6757e-01, -5.3483e-03,  3.1485e-01, -3.2587e-01, -8.8365e-02,
          2.4172e-01,  1.7982e-01,  3.3085e-01, -2.0571e-01, -2.7982e-02,
          2.8920e-01, -1.2191e-01, -3.7320e-01,  4.6051e-02, -2.3296e-01,
         -2.3272e-01, -4.9195e-02,  9.7081e-02, -8.8512e-02, -5.6786e-02,
         -2.2798e-01,  2.4579e-02, -1.

In [ ]:
# vocab을 새롭게 추가했다면, 반드시 model의 embedding layer사이즈를 늘려주세요!
print(model.get_input_embeddings())
model.resize_token_embeddings(tokenizer.vocab_size + added_token_num)
print(model.get_input_embeddings())
# 119547 -> 119549

Embedding(119549, 768)
Embedding(119549, 768)


In [ ]:
# [ClS] 토큰을 활용해 문장의 유사도를 측정할 수 있다.
sent1 = tokenizer("오늘 하루 어떻게 보냈나요?", return_tensors="pt")
sent2 = tokenizer("오늘은 어떤 하루를 보내셨나요?", return_tensors="pt")
sent3 = tokenizer("이순신은 조선 중기의 무신이다.", return_tensors="pt")
sent4 = tokenizer("깟뻬뜨랑 리뿔이 뜨럽거 므리커럭이 케쇽 냐왜쇼 우뤼갸 쳥쇼섀료다혀뚜여", return_tensors="pt")


In [ ]:
outputs = model(**sent1)
sent_1_pooler_output = outputs.pooler_output

outputs = model(**sent2)
sent_2_pooler_output = outputs.pooler_output

outputs = model(**sent3)
sent_3_pooler_output = outputs.pooler_output

outputs = model(**sent4)
sent_4_pooler_output = outputs.pooler_output

In [ ]:
from torch import nn

cos = nn.CosineSimilarity(dim = 1, eps = 1e-6)
print(cos(sent_1_pooler_output, sent_2_pooler_output))

tensor([0.9757], grad_fn=<DivBackward0>)


In [ ]:
print(cos(sent_2_pooler_output, sent_3_pooler_output))

tensor([0.6075], grad_fn=<DivBackward0>)


In [ ]:
print(cos(sent_3_pooler_output, sent_4_pooler_output))

tensor([0.5997], grad_fn=<DivBackward0>)


In [ ]:
print(cos(sent_1_pooler_output, sent_4_pooler_output))

tensor([0.9258], grad_fn=<DivBackward0>)
